# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Florida Boat Sales
email: sales@flaboatsales.com
description: Florida Boat Sales | Treasure Coast, Stuart, Florida
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.flaboatsales.com" # the base hostname & protocol for your site
phone1: "(772) 985-8885"
phone2: ""

boattrader_url: http://www.boattrader.com/dealers/Florida-Boat-Sales/2980404
boattrader:
  dealer:
    id: 2980404




twitter_username: flaboatsales
github_username:  flbs








# PAGES_REPO_NWO: "http://www.github.com/flbs/flaboatsales"
# or use PAGES_REPO_NWO in the env
repository: flbs/flaboatsales

# Build settings
markdown: kramdown

gems: [bootstrap, autoprefixer-rails, jekyll-sitemap] # jekyll-assets,
sass:
  sass_dir: assets/stylesheets

# stylesheet:


#assets:
#  compress:
#      css: true
#      js: true
#  features:
#    automatic_img_size: false
#  sources:
#    - assets/vendor
#    - assets/fonts
#    - assets/images
#    - assets/javascripts
#    - assets/stylesheets

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - script/*

ga_analytics: # Add Google Analytics tracking code

name: Florida Boat Sales

permalink: pretty